# Generated by Django 5.0.6 on 2024-05-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=50)),
                ('precio', models.PositiveBigIntegerField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
    ]
