# Generated by Django 5.0.6 on 2024-05-08 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveBigIntegerField()),
                ('celular', models.PositiveBigIntegerField()),
                ('correo', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveBigIntegerField()),
                ('celular', models.PositiveBigIntegerField()),
                ('correo', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveBigIntegerField()),
                ('celular', models.PositiveBigIntegerField()),
                ('correo', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveBigIntegerField()),
                ('celular', models.PositiveBigIntegerField()),
                ('correo', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
                ('estado_pedido', models.CharField(choices=[('C', 'Cajero'), ('V', 'Vendedor'), ('S', 'Supervisor')], max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='stock_estado',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_cantidad',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('metodo_pago', models.CharField(choices=[('C', 'Credito'), ('D', 'Debito'), ('E', 'Efectivo')], max_length=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pedido', models.CharField(choices=[('P', 'Pedido en Proceso'), ('R', 'Pedido rechazado'), ('E', 'Pedido enviado')], max_length=1)),
                ('soli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.compra')),
            ],
        ),
    ]
