# Generated by Django 5.0.6 on 2024-05-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bodeguero_cliente_contador_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigoProducto',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
