# Generated by Django 5.0.6 on 2024-05-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto_codigoproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigoProducto',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
