# Generated by Django 5.0.6 on 2024-05-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_compra_metodo_entrega_solicitud_pago_realizado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='estado_pedido',
            new_name='cargo',
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigoProducto',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
